# coding: utf-8




import pprint
import re  # noqa: F401

import six

from zuora_client.models.get_taxation_item_typewith_success import GETTaxationItemTypewithSuccess  # noqa: F401,E501


class GETTaxationItemListType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'taxation_items': 'list[GETTaxationItemTypewithSuccess]'
    }

    attribute_map = {
        'success': 'success',
        'taxation_items': 'taxationItems'
    }

    def __init__(self, success=None, taxation_items=None):  # noqa: E501
        """GETTaxationItemListType - a model defined in Swagger"""  # noqa: E501

        self._success = None
        self._taxation_items = None
        self.discriminator = None

        if success is not None:
            self.success = success
        if taxation_items is not None:
            self.taxation_items = taxation_items

    @property
    def success(self):
        """Gets the success of this GETTaxationItemListType.  # noqa: E501

        Returns `true` if the request was processed successfully.  # noqa: E501

        :return: The success of this GETTaxationItemListType.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this GETTaxationItemListType.

        Returns `true` if the request was processed successfully.  # noqa: E501

        :param success: The success of this GETTaxationItemListType.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def taxation_items(self):
        """Gets the taxation_items of this GETTaxationItemListType.  # noqa: E501

        Container for taxation items.   # noqa: E501

        :return: The taxation_items of this GETTaxationItemListType.  # noqa: E501
        :rtype: list[GETTaxationItemTypewithSuccess]
        """
        return self._taxation_items

    @taxation_items.setter
    def taxation_items(self, taxation_items):
        """Sets the taxation_items of this GETTaxationItemListType.

        Container for taxation items.   # noqa: E501

        :param taxation_items: The taxation_items of this GETTaxationItemListType.  # noqa: E501
        :type: list[GETTaxationItemTypewithSuccess]
        """

        self._taxation_items = taxation_items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GETTaxationItemListType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GETTaxationItemListType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
