# coding: utf-8




import pprint
import re  # noqa: F401

import six


class POSTEntityConnectionsType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'target_entity_id': 'str'
    }

    attribute_map = {
        'target_entity_id': 'targetEntityId'
    }

    def __init__(self, target_entity_id=None):  # noqa: E501
        """POSTEntityConnectionsType - a model defined in Swagger"""  # noqa: E501

        self._target_entity_id = None
        self.discriminator = None

        self.target_entity_id = target_entity_id

    @property
    def target_entity_id(self):
        """Gets the target_entity_id of this POSTEntityConnectionsType.  # noqa: E501

        The ID of the target entity that you want to connect with. You can get the entity Id using the Multi-entity: Get entities call.   # noqa: E501

        :return: The target_entity_id of this POSTEntityConnectionsType.  # noqa: E501
        :rtype: str
        """
        return self._target_entity_id

    @target_entity_id.setter
    def target_entity_id(self, target_entity_id):
        """Sets the target_entity_id of this POSTEntityConnectionsType.

        The ID of the target entity that you want to connect with. You can get the entity Id using the Multi-entity: Get entities call.   # noqa: E501

        :param target_entity_id: The target_entity_id of this POSTEntityConnectionsType.  # noqa: E501
        :type: str
        """
        if target_entity_id is None:
            raise ValueError("Invalid value for `target_entity_id`, must not be `None`")  # noqa: E501
        if target_entity_id is not None and len(target_entity_id) > 32:
            raise ValueError("Invalid value for `target_entity_id`, length must be less than or equal to `32`")  # noqa: E501

        self._target_entity_id = target_entity_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(POSTEntityConnectionsType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, POSTEntityConnectionsType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
