# coding: utf-8




import pprint
import re  # noqa: F401

import six


class POSTHMACSignatureType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_key': 'str',
        'method': 'str',
        'name': 'str',
        'page_id': 'str',
        'uri': 'str'
    }

    attribute_map = {
        'account_key': 'accountKey',
        'method': 'method',
        'name': 'name',
        'page_id': 'pageId',
        'uri': 'uri'
    }

    def __init__(self, account_key=None, method=None, name=None, page_id=None, uri=None):  # noqa: E501
        """POSTHMACSignatureType - a model defined in Swagger"""  # noqa: E501

        self._account_key = None
        self._method = None
        self._name = None
        self._page_id = None
        self._uri = None
        self.discriminator = None

        if account_key is not None:
            self.account_key = account_key
        self.method = method
        if name is not None:
            self.name = name
        if page_id is not None:
            self.page_id = page_id
        self.uri = uri

    @property
    def account_key(self):
        """Gets the account_key of this POSTHMACSignatureType.  # noqa: E501

        Customer account number or ID.  Specifies this field only when creating signatures for Create payment method.   # noqa: E501

        :return: The account_key of this POSTHMACSignatureType.  # noqa: E501
        :rtype: str
        """
        return self._account_key

    @account_key.setter
    def account_key(self, account_key):
        """Sets the account_key of this POSTHMACSignatureType.

        Customer account number or ID.  Specifies this field only when creating signatures for Create payment method.   # noqa: E501

        :param account_key: The account_key of this POSTHMACSignatureType.  # noqa: E501
        :type: str
        """

        self._account_key = account_key

    @property
    def method(self):
        """Gets the method of this POSTHMACSignatureType.  # noqa: E501

        Possible values are: 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'.   # noqa: E501

        :return: The method of this POSTHMACSignatureType.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this POSTHMACSignatureType.

        Possible values are: 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'.   # noqa: E501

        :param method: The method of this POSTHMACSignatureType.  # noqa: E501
        :type: str
        """
        if method is None:
            raise ValueError("Invalid value for `method`, must not be `None`")  # noqa: E501

        self._method = method

    @property
    def name(self):
        """Gets the name of this POSTHMACSignatureType.  # noqa: E501

        Account name.  Specifies this field only when creating signatures for Create account.   # noqa: E501

        :return: The name of this POSTHMACSignatureType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this POSTHMACSignatureType.

        Account name.  Specifies this field only when creating signatures for Create account.   # noqa: E501

        :param name: The name of this POSTHMACSignatureType.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def page_id(self):
        """Gets the page_id of this POSTHMACSignatureType.  # noqa: E501

        The page id of your Payment Pages 2.0 form. Click **Show Page Id** next to the Payment Page name in the Hosted Page List to retrieve the page id.  Specifies this field only when creating signatures for RSA Signatures.   # noqa: E501

        :return: The page_id of this POSTHMACSignatureType.  # noqa: E501
        :rtype: str
        """
        return self._page_id

    @page_id.setter
    def page_id(self, page_id):
        """Sets the page_id of this POSTHMACSignatureType.

        The page id of your Payment Pages 2.0 form. Click **Show Page Id** next to the Payment Page name in the Hosted Page List to retrieve the page id.  Specifies this field only when creating signatures for RSA Signatures.   # noqa: E501

        :param page_id: The page_id of this POSTHMACSignatureType.  # noqa: E501
        :type: str
        """

        self._page_id = page_id

    @property
    def uri(self):
        """Gets the uri of this POSTHMACSignatureType.  # noqa: E501

        The URI of the API object the customer will make a CORS enabled call to. e.g. \"https://rest.zuora.com/v1/payment-methods/credit-cards\"   # noqa: E501

        :return: The uri of this POSTHMACSignatureType.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this POSTHMACSignatureType.

        The URI of the API object the customer will make a CORS enabled call to. e.g. \"https://rest.zuora.com/v1/payment-methods/credit-cards\"   # noqa: E501

        :param uri: The uri of this POSTHMACSignatureType.  # noqa: E501
        :type: str
        """
        if uri is None:
            raise ValueError("Invalid value for `uri`, must not be `None`")  # noqa: E501

        self._uri = uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(POSTHMACSignatureType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, POSTHMACSignatureType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
